apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cohsqtj19-go 
  janus-idp.io/tekton: cohsqtj19-go
  backstage.io/kubernetes-id: cohsqtj19-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cohsqtj19-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  